### ISSUE TITLE
1500 lines of C++ code

### ISSUE THREAD

**Issue by Mazyod** [stefanceriu/SCXcodeMiniMap#29]
Hey,

Thanks for the great plugin. I love it, however, it renders Xcode unusable when I am working on a C++ project, and especially with a huge file (1500+ lines of code).

I haven't looked at the implementation, but I would guess the only cause is that the minimap updates are too often. I mean, they don't have to be real time, right? The point of minimaps (IMHO) is to get a glance of how long the file is, and get an idea of where certain code might be.

Thanks,

**Comment by stefanceriu** [comment]
So I just pushed v2.0, performance shouldn't be a problem anymore :)

**Comment by Mazyod** [comment]
Sick, been waiting for this one! Productivity++
Thanks!

**Comment by stefanceriu** [comment]
I certainly hope you won't have any problems with it and go productivity-- :))
Either way, please let me know how it goes.

**Comment by Gui13** [comment]
Sadly for me: #39 :(
