### ISSUE TITLE
overlaped minimap views

### ISSUE THREAD

**Issue by blueprajna** [stefanceriu/SCXcodeMiniMap#34]
![screen shot 2014-11-24 at 1 04 40 pm](https://cloud.githubusercontent.com/assets/424569/5160803/82c0f57e-73da-11e4-9996-f42c0d061d5f.png)

many minimap views are overlaped in .m files.
.h files are ok.

xcode 6.1, os x 10.10.1, MacBook Pro (Retina, 15-inch, Mid 2014)

**Comment by stefanceriu** [comment]
I wasn't really able to reproduce this but considering I rewrote the whole thing for v2.0 I'm thinking it shouldn't be a problem anymore. I'll close this issues until further notice..

Cheers,
Stefan
