### ISSUE TITLE
Add option to disable scroll animation

### ISSUE THREAD

**Issue by mike-lischke** [stefanceriu/SCXcodeMiniMap#42]
Looks like minimap uses an animation to scroll to a given position. Can this be made optional? The animation significantly slows down quick navigation. Thank you.

**Comment by stefanceriu** [comment]
I disabled the animations while dragging on the minimap and only left them for when clicking. If you would like to disable then completely then change the shouldAnimateContentOffset bool in the handleMouseEvent: method and rebuild the project.
