### ISSUE TITLE
Feature: autohide for small files

### ISSUE THREAD

**Issue by dev4dev** [stefanceriu/SCXcodeMiniMap#44]
I'm not really sure will it be useful, but can you add option for autohiding MiniMap if editor doesn't have vertical scroll?
I think it's better not to remove it completely, but just set width to = 0, for better performance.

**Comment by stefanceriu** [comment]
Hey, sorry for the late reply. Just to let you know I do plan on adding it, just haven't gotten around to it :)

**Comment by stefanceriu** [comment]
Finally got around to building this and it's available in the new v2.3 prerelease. It will be disabled by default so you need to enable it from the view menu.
Let me know how it goes.
