### ISSUE TITLE
Errors get under the minimap making them impossible to read

### ISSUE THREAD

**Issue by haaakon** [stefanceriu/SCXcodeMiniMap#45]
![screenshot 2015-03-24 08 21 59](https://cloud.githubusercontent.com/assets/1579465/6797178/e4f57990-d1fe-11e4-83ca-416fcbe64797.png)

using xcode 6.2. Also seems like text can also end up under the minimap.

**Comment by stefanceriu** [comment]
Hey, I'm having problems reproducing this. The weird thing is that I am resizing the main editor textView so that small red bit on the far right shouldn't be there.
Anything special you are doing and are you sure you're on the latest version ?
