### ISSUE TITLE
Xcode preference "Show live issues" gets jammed

### ISSUE THREAD

**Issue by JaxGit** [stefanceriu/SCXcodeMiniMap#46]
I had Xcode 5.1.1 and Xcode 6.1 coexist on my laptop with SCXcodeMiniMap installed from Alcatraz and everything works fine. 
After I upgrade the latter to Xcode 6.2, I can't get live issues and errors on both version even if I reinstall both or clear all DerivedData for re-indexing.
I have to remove SCXcodeMiniMap for a while.

**Comment by stefanceriu** [comment]
I usually have live issues disabled but I am seeing this on Xcode 6.3. I'll try to figure out what's wrong and fix it asap.

**Comment by stefanceriu** [comment]
Should be okay now but please do let me know if you have any more problems with it.

**Comment by JaxGit** [comment]
It works fine on Xcode 6.3.2 now, thanks mate~
