### ISSUE TITLE
Use trackpad, the map following the last focus

### ISSUE THREAD

**Issue by Weever** [stefanceriu/SCXcodeMiniMap#47]
In Xcode v6.2, MiniMap v2.0.
first, my focus in the top of the page, in this time, i scroll the map to the bottom of the page, 
and use trackpad scroll page, the page scroll to top(first focus position) right now.

**Comment by StevenMasini** [comment]
Yes! The same bug occur with me too. If I use the trackpad instead of the minimap to scroll, the view will automatically scroll back to the position where the minimap is set.
That's an very annoying bug :S

**Comment by stefanceriu** [comment]
Hey, I'm having troubles reproducing this. Can you guys give me a bit more to go on?
What options are enabled on the Minimap, does it happen on all source files, Xcode version etc. ?

**Comment by StevenMasini** [comment]
Hey Stef,
I just reinstall minimap on my Macbook Pro 13" and I get the bug directly. I don't know why, but I will try later with my Macbook 15" to see if there is a difference.

![screen shot 2015-04-22 at 12 38 16 pm](https://cloud.githubusercontent.com/assets/1907562/7267372/bc840ac6-e8ec-11e4-94aa-cb083b93b7d3.png)

I'm at your service if you need more details.

**Comment by StevenMasini** [comment]
Ok I figured out why this bug happens!
If I select the option "Hide editor scroller" then the problem occur. But if I don't hide the editor scroller then everything is right.

Btw my XCode Version is 6.3 but it also happened before with XCode 6.2, and it happens with any kind of file I think.

**Comment by stefanceriu** [comment]
Perfect, we have ourselves a starting point :)
I'll try to figure out what's wrong and fix it asap.

**Comment by stefanceriu** [comment]
Should be fixed now and although this might look like a really hacky approach it does work better than all the others I tried.
