### ISSUE TITLE
Support for Xcode 6.4 beta?

### ISSUE THREAD

**Issue by MakeZL** [stefanceriu/SCXcodeMiniMap#49]
Hey, Im is MakeZL.
Xcode 6.4 beta UUID is 992275C1-432A-4CF7-B659-D84ED6D42D3F.

**Comment by stefanceriu** [comment]
Hi, how about a pull request ?

**Comment by MakeZL** [comment]
I create a new pull request request.

**Comment by stefanceriu** [comment]
Cool, thanks. Please check my comment on the pull request.
