### ISSUE TITLE
Other plugins can't be installed after this plugin.

### ISSUE THREAD

**Issue by MKGitHub** [stefanceriu/SCXcodeMiniMap#51]
If I install this plugin, other plugins can't be installed after this plugin. So I have to uninstall this plugin, install other plugins and then reinstall this plugin!

**Comment by stefanceriu** [comment]
Now that's a bit weird, tried it now with SCXcodeMinimap and SCXcodeSwitchExpander and it seems to be working. What other plugins were you trying to install when you saw this ?
