### ISSUE TITLE
Won't build if Xcode not in /Applications

### ISSUE THREAD

**Issue by hyperjeff** [stefanceriu/SCXcodeMiniMap#53]
I have Xcode in /Applications/Developer, and I've tried to tweak the project to build for this location without success.

**Comment by stefanceriu** [comment]
How about you just download the already built version from here https://github.com/stefanceriu/SCXcodeMiniMap/releases/tag/v2.1 ?

**Comment by hyperjeff** [comment]
Oh, man, didn't even think of that. Thanks! that works great.

**Comment by stefanceriu** [comment]
Perfect ! :)
