### ISSUE TITLE
Plugin not working in Xcode 6.3.2 

### ISSUE THREAD

**Issue by Prince2k3** [stefanceriu/SCXcodeMiniMap#54]
Not sure what Apple has done but this no longer works in Xcode 6.3.2.

**Comment by stefanceriu** [comment]
They didn't really do anything wrong :) 
Each Xcode version has a plugin compatibility UUID associated to it and which plugins need to adopt.

stefanceriu/SCXcodeMinimap@83359dc36e7476bab6c0d43b612c73edadeb7798
