### ISSUE TITLE
Feature: Show errors and warnings.

### ISSUE THREAD

**Issue by Zatoichy** [stefanceriu/SCXcodeMiniMap#55]
Please add the display of errors and warnings.

**Comment by stefanceriu** [comment]
I'll give it a shot, but I might take a while

**Comment by stefanceriu** [comment]
It's been a slow day so I figured I might as well do something productive :)
I pushed an initial version of warnings and errors highlighting to develop so you will have to build it yourself. Any help testing it would be much appreciated.
I plan on using it the next couple of days and, if it's all good, push it to master towards the end of the week.

**Comment by Zatoichy** [comment]
It looks great!
It seems working.
It is a pity that in my personal and work Mac(MBP 2010, iMac 2013) begins to slow scrolling in xcode when using your plugin.

**Comment by stefanceriu** [comment]
I made a couple of changes while working on #56 and it should be a bit better now, at least when constructing the breakpoint and build issue ranges.
It's all pretty much down to how long your source files, but if you find it too annoying you can try playing around with the 'kDurationBetweenInvalidations' const. 
For what it's worth it's pretty much unnoticeable on my MacBook Pro Retina, Late 2013.
