### ISSUE TITLE
Highlight symbol occurrences à la ProgressiveScroll

### ISSUE THREAD

**Issue by stefanceriu** [stefanceriu/SCXcodeMiniMap#56]
Find a way to hook into Xcode's built in ‘Highlight instances of selected symbol’ feature and also show those occurrences on the Minimap.

Should end up with something like this: ![](https://visualstudiogallery.msdn.microsoft.com/873d4c86-7827-4d51-95e9-6eb44c0d3287/image/file/83254/1/ProgressiveScroll.png?Id=83254)

**Comment by stefanceriu** [comment]
Now implemented for v2.2 https://github.com/stefanceriu/SCXcodeMiniMap/releases/tag/v2.2

**Comment by despoke** [comment]
Hi, I downloaded and installed v2.2 from source code.
However when I hightlight a selected symbol (CTRL+E, CTRL+F), it will not show up in the minimap, or am I doing something wrong? I attached a screenshot, where I highlighted the symbol "cgn" which is visible in the main window, but not in the minimap.

The "View->Minimap->Highlight selected symbol" option is ticked.

![screen shot 2015-05-27 at 00 51 17](https://cloud.githubusercontent.com/assets/12613329/7816759/19015342-040b-11e5-8c53-055cabbb945a.png)

**Comment by stefanceriu** [comment]
Hey,

It's not linked to the search box, it's linked to Xcode's "Highlight instances of selected symbol" feature here:

![](https://cloud.githubusercontent.com/assets/637564/7817263/c5718de4-03cb-11e5-86e8-2bba67b751ae.png)

**Comment by despoke** [comment]
I see!
I have the "Hightlight instances of selected symbol" already enabled and set up to 0 seconds, but it never highlighted anything for me... But i'm also on XCode 6.1 ...
I'll update to latest XCode version tomorrow and get back to you.
Thx!

**Comment by stefanceriu** [comment]
Cool, let me know how it goes ;)

**Comment by despoke** [comment]
I updated to XCode 6.3.2. Unfortunately the "Highlight instances of selected symbols" is still not working for me. I would probably need to uninstall and cleanly re-install XCode to try fixing this...
