### ISSUE TITLE
XCode version editor (comparison) lost previous focus and scrolls to the top

### ISSUE THREAD

**Issue by JaxGit** [stefanceriu/SCXcodeMiniMap#61]
In XCode 6.3.2, MiniMap installed from Alcatraz

Given there are previous focus lines in some source files, and no matter the MiniMap shows or hide, 
When every time I switch from the Standard/Assistant editor to Version editor (Comparison mode), or switch between these source files with Version editor (Comparison mode), 
Then the previous focus line of the current file will be lost, and both revision windows of the Version editor will scroll to the top.

**Comment by stefanceriu** [comment]
Cool, thank you for raising the issue. I'll try to fix it asap.

**Comment by stefanceriu** [comment]
Right, I finally managed to figure out what causes this problem and I'm pretty sure I managed to fix it.
The fix is only available develop, mind giving it a go and letting me know if causes any issues for you ?

**Comment by JaxGit** [comment]
Great, the develop branch build works fine on XCode Version 6.4 (6E35b) now. Thanks mate!

**Comment by stefanceriu** [comment]
Perfect, pushed it to master.
Thank you !
