### ISSUE TITLE
SCXcodeMiniMap warning when loading a Playground 

### ISSUE THREAD

**Issue by Prince2k3** [stefanceriu/SCXcodeMiniMap#62]
Hi! I'm getting an console error when playground loads. The error is as follows 

com.apple.dt.Xcode.Playground[12396]: WARNING: Failed to load plugin at path:  ... The bundle “SCXcodeMinimap” couldn’t be loaded because it is damaged or missing necessary resources

Though it is a warning would be nice to prevent this from happening. I'm sure Apple is receiving these types of logs and thus the reason for them to try put up warnings about installing plugins

**Comment by stefanceriu** [comment]
Hey, that's indeed a bit annoying but the problem is that I have no idea how to fix it. The minimap relies on IDESourceEditor.ideplugin and starting Xcode with a playground doesn't know how to load it up.
Nothing I tried so far works so ideas are welcome..

**Comment by stefanceriu** [comment]
This doesn't seem to be happening anymore under Xcode 8.3.1.
