### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by gerchicov-bp** [stefanceriu/SCXcodeMiniMap#63]
1. What about to distinguish ```#pragma mark``` and other preprocessor macro? The reason is this macro  is usually to separate code in several chunks only
2. You have an option to hide minimap fully but if I have previously chosen "highlight main editor" then it will have been hidden too. What about to split this option into 2 independent ones?

**Comment by stefanceriu** [comment]
They are both good ideas but, unfortunately, I don't have the bandwidth to implement them at the moment.

I will be more than happy to accept a pull request though :)
