### ISSUE TITLE
Xcode crashed when tap BackSpace twice 

### ISSUE THREAD

**Issue by Zcgong** [stefanceriu/SCXcodeMiniMap#72]
If I use SCXcodeMiniMap, Xcode crashed when taped BackSpace twice. Remove SCXcodeMiniMap this issue fixed.

**Comment by stefanceriu** [comment]
![2372616](https://cloud.githubusercontent.com/assets/637564/10428421/3bc311f4-70e9-11e5-8805-7428259c0eb5.jpg)
