### ISSUE TITLE
MiniMap obscuring right hand side of code in Xcode word-wrap mode

### ISSUE THREAD

**Issue by DanielAsher** [stefanceriu/SCXcodeMiniMap#78]
MiniMap is overlaying the text editor in Xcode 7.2.1 so that the end of lines are obscured and readability is harmed. 

Please let me know if this is verified or fixed in a previous commit.

thanks for the great plugin!

<img width="869" alt="screen shot 2016-02-29 at 15 28 36" src="https://cloud.githubusercontent.com/assets/7915553/13399130/a66af480-def9-11e5-9090-4c96ccdadd76.png">

**Comment by stefanceriu** [comment]
Hi Daniel,

There was a similar problem a while back (#59) and I think I messed up by removing that async dispatch in a later update.
I added it back on develop, can you please give it a go ?

Thanks,
Stefan

**Comment by DanielAsher** [comment]
Hi Stefan,

I've tested both master and develop and it seems that neither have a problem - but both express this behaviour when used with [XVim](https://github.com/XVimProject/XVim).

Tricky, no doubt. Please try out XVim to see if you can reproduce the problem.

many thanks and all power to you,

Daniel

**Comment by DanielAsher** [comment]
I've cross-reported the issue https://github.com/XVimProject/XVim/issues/930

**Comment by stefanceriu** [comment]
Oh, okay, that changes things. I was able to reproduce it on my side and I'll try to dig into XVim to see what exactly is causing it (most likely a change in the source code editor's containerView autoresizing masks).

**Comment by DanielAsher** [comment]
cool! thanks so much for digging in :)
