### ISSUE TITLE
Xcode 8 extension support

### ISSUE THREAD

**Issue by alexkaessner** [stefanceriu/SCXcodeMiniMap#85]
**Any chance that MiniMap supports the official new Xcode 8 Extensions?**

I didn't tested it on Xcode 8 beta yet, but it seems like "classic" plugins are broken.

**Comment by githubjason** [comment]
Please I want to use it in xcode 8.2..

**Comment by Manloff** [comment]
I move it to the Xcode plugins folder, but it doesn't work on Xcode 8.2, hope

**Comment by stefanceriu** [comment]
Hi guys,

Sorry for the ridiculously late reply but I just didn't get a chance to dig into it and stop it from crashing on Xcode 8.
I finally managed to do that this week and I pushed a new release here https://github.com/stefanceriu/SCXcodeMiniMap/releases/tag/v.2.3.10

Now, Xcode Extensions are not nearly powerful enough to allow me to build the minimap on top of them so "classic" plugins are all we get.
Getting them back is not really a big problem, but it does involve unsigning Xcode so please read more about it here https://github.com/alcatraz/Alcatraz/issues/475

I also found https://github.com/inket/update_xcode_plugins to be the simplest way to get everything working again.

Cheers,
Stefan
